name: nginx Manu

on:
  push:
    branches: 
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Log in into the container registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.ContainerUsername }}
        password: ${{ secrets.ContainerPassword }}
    - name: Build e push container umage to registry
      uses: docker/build-push-action@v2
      with:
        context: src/
        push: true
        tags: index.docker.io/${{ secrets.ContainerUsername }}/nginx_manu:${{ github.sha }}
        file: src/Dockerfile
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'nginx_manu'
          slot-name: 'production'
          publish-profile: ${{ secrets.PublishProfile }}
          images: 'index.docker.io/${{ secrets.ContainerUsername }}/nginx_manu:${{ github.sha }}'
        
